yss14/musicshare

- .dependabot/config.yml
* dependatbot ignore cassandra-schema-builder
> feature: create custom dependabot config

- package.json
- projects/backend/src/__test__/genre-service.test.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/database/fixtures.ts
- projects/backend/src/database/schema/V1.ts
- projects/backend/src/database/schema/make-database-schema.ts
- projects/backend/src/database/schema/tables.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/index.ts
- projects/backend/src/models/GenreModel.ts
- projects/backend/src/models/SongType.ts
- projects/backend/src/models/interfaces/Genre.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/services/GenreService.ts
- projects/backend/src/services/SongTypeService.ts
- projects/backend/src/utils/song-meta/song-meta-formats/id3/ID3MetaData.ts
* add genre interface, model, service, and resolver integration
resolves #84
> feature: backend genres

- projects/backend/src/__test__/artist-service.test.ts
- projects/backend/src/__test__/mocks/SongServiceMock.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/index.ts
- projects/backend/src/models/ArtistModel.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/services/ArtistService.ts
- projects/backend/src/services/SongService.ts
* add share resolver artist query
* add artist service and model
resolves #85
> feature: backend add artist query

- projects/backend/package-lock.json
- projects/backend/package.json
- projects/backend/src/__test__/fixtures/song-query.ts
- projects/backend/src/__test__/mp3-song-duration.test.ts
- projects/backend/src/database/schema/V1.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/index.ts
- projects/backend/src/job-queues/SongUploadProcessingQueue.ts
- projects/backend/src/models/SongModel.ts
- projects/backend/src/models/interfaces/ISong.ts
- projects/backend/src/static/debug/file-upload.html
- projects/backend/src/typings/mp3-duration.d.ts
- projects/backend/src/utils/song-meta/song-meta-formats/id3/MP3SongDuration.ts
- projects/frontend/src/App.tsx
- projects/frontend/src/components/Dropzone.tsx
- projects/frontend/src/context/configContext.ts
- projects/frontend/src/hooks/use-config.ts
- projects/frontend/src/utils/upload/upload.ts
- projects/frontend/src/utils/upload/uploadFile.ts
* add song duration to song queries
* add song duration to meta data extraction
* fix upload in frontend to support single/multi uploads
> feature: song duration and fix upload

- projects/backend/src/__test__/mocks/SongServiceMock.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/services/SongService.ts
- projects/cassandra-schema-builder/src/__test__/table-queries.test.ts
- projects/cassandra-schema-builder/src/table.ts
* add query to retrieve dirty songs to handle updated song data
* fix set dateLastEdit during song mutation
* add selectWhere query to cassandra tables
> feature: backend get dirty songs query

- projects/backend/src/__test__/playlist-resolver.test.ts
- projects/backend/src/resolvers/PlaylistResolver.ts
- projects/backend/src/services/PlaylistService.ts
> feature: backend remove songs from playlists mutation

- package-lock.json
- package.json
- projects/backend/jest.json
- projects/backend/package.json
- projects/backend/src/__test__/auth.test.ts
- projects/backend/src/__test__/playlist-resolver.test.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/__test__/user-resolver.test.ts
- projects/backend/src/__test__/utils/graphql.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/auth/auth-middleware.ts
- projects/backend/src/auth/middleware/auth-selectors.ts
- projects/backend/src/auth/middleware/playlist-auth.ts
- projects/backend/src/auth/middleware/share-auth.ts
- projects/backend/src/auth/middleware/song-auth.ts
- projects/backend/src/auth/permissions.ts
- projects/backend/src/index.ts
- projects/backend/src/resolvers/PlaylistResolver.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/backend/src/resolvers/UserResolver.ts
- projects/backend/src/server/GraphQLServer.ts
- projects/backend/src/services/ShareService.ts
- projects/backend/src/types/context.ts
* introduce permissions
* introduce and apply custom decorator middleware to check permissions
* remove userid param from user query
> feature: backend add permissions

- projects/backend/package-lock.json
- projects/backend/src/__test__/auth.test.ts
- projects/backend/src/__test__/playlist-resolver.test.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/auth/middleware/auth-selectors.ts
- projects/backend/src/database/schema/V1.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/index.ts
- projects/backend/src/job-queues/SongUploadProcessingQueue.ts
- projects/backend/src/models/PlaylistModel.ts
- projects/backend/src/models/SongModel.ts
- projects/backend/src/resolvers/PlaylistResolver.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/backend/src/services/PlaylistService.ts
- projects/backend/src/services/SongService.ts
- projects/cassandra-schema-builder/src/index.ts
- projects/cassandra-schema-builder/src/table.ts
* update song mutation also updates all song reference in playlists
* rename id column names of song and playlist to prefixed names
> fix: update playlist songs

- projects/backend/src/__test__/fixtures/song-query.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/database/schema/V1.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/inputs/SongInput.ts
- projects/backend/src/job-queues/SongUploadProcessingQueue.ts
- projects/backend/src/models/SongModel.ts
> feature: backend song tags

- .dockerignore
- projects/backend/Dockerfile
- projects/backend/src/database/core-database.ts
* add .dockerignore and backend Dockerfile
* fix cassandra connection user/password argument order
> feature: backend add dockerfile

- README.md
- projects/frontend/src/components/Dropzone.tsx
- projects/frontend/src/components/HeaderMenu.tsx
- projects/frontend/src/components/RouteWrapper.tsx
- projects/frontend/src/components/Spinner.tsx
- projects/frontend/src/components/form/Dropdown.tsx
- projects/frontend/src/components/menu/Menu.tsx
- projects/frontend/src/components/modals/song-modal/SongForm.tsx
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/pages/share/PlaylistSongs.tsx
- projects/frontend/src/pages/share/ShareSongs.tsx
- projects/frontend/src/utils/format-duration.ts
* add loading spinner component
* use spinner for playlists and song table
* remove remote shares option from share navigation
* add time column to song table
* add @fewhnhouse to contributors
> feature: frontend loading spinner

- package-lock.json
- projects/backend/package-lock.json
- projects/backend/src/__test__/mocks/ShareServiceMock.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/args/share-args.ts
- projects/backend/src/auth/permissions.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/services/ShareService.ts
- projects/cassandra-schema-builder/package-lock.json
- projects/frontend/package-lock.json
> feature: backend add share mutation

- .travis.yml
- package.json
- projects/frontend/src/Apollo.ts
- projects/frontend/src/components/MainLayout.tsx
- projects/frontend/src/components/Player.tsx
- projects/frontend/src/components/menu/SharePlaylistsSidebar.tsx
- projects/frontend/src/components/modals/contextmenu/ContextMenu.tsx
- projects/frontend/src/components/modals/playlist-picker/PlaylistPicker.tsx
- projects/frontend/src/components/routing/Routing.tsx
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/context/ShareIDContext.ts
- projects/frontend/src/graphql/client/queries/share-query.ts
- projects/frontend/src/graphql/mutations/add-songs-to-playlist.ts
- projects/frontend/src/graphql/mutations/login-mutation.ts
- projects/frontend/src/graphql/mutations/update-song-mutation.ts
- projects/frontend/src/graphql/queries/artists-query.ts
- projects/frontend/src/graphql/queries/playlist-songs.ts
- projects/frontend/src/graphql/queries/shares-query.ts
- projects/frontend/src/graphql/queries/user-query.ts
- projects/frontend/src/hooks/use-share.ts
- projects/frontend/src/hooks/use-song-utils.ts
- projects/frontend/src/pages/login/LoginForm.tsx
- projects/frontend/src/pages/share/PlaylistSongs.tsx
- projects/frontend/src/pages/share/Share.tsx
- projects/frontend/src/pages/share/ShareSongs.tsx
- projects/frontend/src/pages/share/SongContextMenu.tsx
- projects/frontend/src/player/player-hook.ts
- projects/frontend/src/player/player.ts
- projects/frontend/src/utils/filter-null.ts
* add basic structure for creating context menus
* create `SongContextMenu`
* integrate `SongContextMenu` into SongList and PlaylistSongList
> feature: frontend song contextmenu

- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/services/SongService.ts
* share song query returns all songs of linked libraries
* add 4th seed song linked to simon's library
Relates to #804
> feature: revise backend share song query

- projects/backend/src/__test__/song-resolver.test.ts
* add test case foreign song mutation not permitted
Relates to #804
> feature: backend add test case foreign song mutation not permitted

- package-lock.json
- package.json
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/components/song-table/SongTableHeader.tsx
- projects/frontend/src/components/song-table/search/SongSearch.tsx
- projects/frontend/src/components/song-table/search/SongSearchOptionsPopover.tsx
- projects/frontend/src/components/song-table/search/search-types.ts
- projects/frontend/src/graphql/queries/song-search.ts
- projects/frontend/src/hooks/use-defered-flag.ts
- projects/frontend/src/hooks/use-prev-value.ts
- projects/frontend/src/hooks/use-resetting-state.ts
- projects/frontend/src/pages/share/SongsView.tsx
* add search bar with basic search options `mode` and `matcher`
* fetch and display search results from backend
* filter current song view
* enable drag'n'drop of search results
> feature: frontend song search

- projects/backend/src/database/schema/V1.ts
- projects/backend/src/database/schema/tables.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/job-queues/SongUploadProcessingQueue.ts
- projects/backend/src/models/SongModel.ts
- projects/backend/src/services/PlaylistService.ts
- projects/backend/src/services/SongService.ts
* remove `share_songs ` table and move share-song relation to `songs` table
* adjust all related queries and test cases
Closes #815
> refactor: backend remove share_songs table and fix all relations

- projects/backend/src/__test__/mocks/ShareServiceMock.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/services/ShareService.ts
* add rename share mutation
* add delete share mutation
* fix share service getSharesOfUser not returning deletes shares
Relates to #850
> feature: backend rename and delete share mutations

- projects/backend/src/__test__/mocks/ShareServiceMock.ts
- projects/backend/src/__test__/mocks/SongServiceMock.ts
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/auth/middleware/auth-selectors.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/inputs/RemoveSongFromLibraryInput.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/backend/src/services/ShareService.ts
- projects/backend/src/services/SongService.ts
* remove song mutation
* fix song query of share when accessing a playlist song referenced from a foreign library
Relates #794
> feature: backend remove song mutation

- projects/backend/src/__test__/mocks/SongServiceMock.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/models/FileSourceModels.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/backend/src/return-types/SongIDUpdate.ts
- projects/backend/src/services/SongService.ts
- projects/frontend/src/Apollo.ts
- projects/frontend/src/graphql/mutations/delete-share-mutation.ts
- projects/frontend/src/graphql/mutations/remove-song-from-library-mutation.ts
- projects/frontend/src/graphql/mutations/remove-songs-from-playlist-mutation.ts
- projects/frontend/src/pages/share/SongContextMenu.tsx
- projects/frontend/src/pages/share/SongsView.tsx
* add context menu entries for remove song from library and playlist
* remove song from library mutation returns array of song id updates
* remove song from library mutation
* remove songs from playlist mutation
* remove song from library copy filter file upload sources
Closes #794
> feature: frontend remove song contextmenu integration

- package-lock.json
- package.json
- projects/backend/src/database/seed.ts
- projects/frontend/src/App.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/components/sidebar/SidebarItem.tsx
- projects/frontend/src/components/sidebar/SidebarSection.tsx
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/pages/share/SongsView.tsx
- projects/frontend/src/types/isMutableRef.ts
* adjust song table rows styling to fit more content and look prettier
* song dblclick to listen, on click no modal
* refine sidebar style and make add button sticky
* virtualize song table
Closes #879
> feature: frontend virtualized song table

- projects/backend/Dockerfile
*  backend dockerfile install gcc, g++, and python before calling npm i
> feature: backend dockerfile install gcc, g++, and python before calling npm i

- projects/backend/Dockerfile
- projects/frontend/Dockerfile
* frontend dockerfile install gcc, g++, and python before calling npm i
> feature: frontend dockerfile install gcc, g++, and python before calling npm i

- package-lock.json
just ran `npm audit fix` to fix some inconsistencies in `package-lock.json`
> chore: fix npm vulnerabilities

- package-lock.json
- package.json
- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/__test__/user-resolver.test.ts
- projects/backend/src/__test__/utils.test.ts
- projects/backend/src/auth/PasswordLoginService.ts
- projects/backend/src/database/versions/SchemaV1.ts
- projects/backend/src/inputs/ChangePasswordInput.ts
- projects/backend/src/inputs/RestorePasswordInput.ts
- projects/backend/src/models/return-models/AcceptInvitationPayloadModel.ts
- projects/backend/src/resolvers/ShareResolver.ts
- projects/backend/src/resolvers/UserResolver.ts
- projects/backend/src/types/errors/NotFound.ts
- projects/backend/src/types/scalars/order-update.ts
- projects/frontend/src/Apollo.ts
- projects/frontend/src/components/HeaderMenu.tsx
- projects/frontend/src/components/modals/ChangePasswordModal.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettings.tsx
- projects/frontend/src/components/routing/Routing.tsx
- projects/frontend/src/graphql/mutations/accept-invitation-mutation.ts
- projects/frontend/src/graphql/mutations/change-password-mutation.ts
- projects/frontend/src/graphql/mutations/restore-password-mutation.ts
- projects/frontend/src/graphql/programmatic/logout.ts
- projects/frontend/src/pages/CustomerActionForm.tsx
- projects/frontend/src/pages/accept-invitation/AcceptInvitation.tsx
- projects/frontend/src/pages/accept-invitation/AcceptInvitationForm.tsx
- projects/frontend/src/pages/login/Login.tsx
- projects/frontend/src/pages/login/LoginForm.tsx
- projects/frontend/src/pages/restore-password/RestorePassword.tsx
- projects/frontend/src/pages/restore-password/RestorePasswordForm.tsx
**Backend**
* add change password mutation with test cases
* add restore password mutation with test cases
* update postgres-schema-builder@1.1.0-beta.2
* register inserts restore token; acceptInvitation also returns restore token
**Frontend**
* show restore token after accepted invitation
* fix cancel icon onClick of share settings modal
* add restore password page with form
* add change password modal
* logout user if user not found error shows up
Closes #961
> feature: password management

- projects/backend/src/database/seed.ts
- projects/backend/src/types/config.ts
* adjust dev seed users email and share name
* change default user password to `WeLoveMusic`
> chore; backend adjust seed

- README.md
- package.json
- projects/frontend/package.json
* improve instructions on docker-compose
* fix `dev` npm script
* readme add troubleshooting section and add postgres related troubleshooting
* fix frontend start command in lerna evironment (due to [`react-scripts@3.4.1`](https://github.com/facebook/create-react-app/issues/8688))
* remove instruction on running the combined dev command, instead start backend and frontend separately
* add instructions on how to login
> chore: improve readme and fix local setup

- package-lock.json
- package.json
- projects/frontend/src/components/modals/song-modal/SongForm.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/components/song-table/SongsView.tsx
- projects/frontend/src/components/song-table/search/SongViewSettings.tsx
- projects/frontend/src/graphql/mutations/add-songs-to-playlist.ts
- projects/frontend/src/pages/share/MainSongsView.tsx
- projects/frontend/src/pages/share/MergedSongs.tsx
- projects/frontend/src/pages/share/PlaylistSongs.tsx
- projects/frontend/src/pages/share/ShareSongs.tsx
* fix songs view internal songs state (and add deep equal compare)
* change label song form "Record Labels"
* don't navigate to newly created playlist
> fix: frontend song view internal songs state

- projects/frontend/src/components/song-table/SongRow.tsx
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/components/song-table/SongTableColumns.tsx
- projects/frontend/src/graphql/mutations/update-playlist-song-order.ts
- projects/frontend/src/graphql/mutations/update-song-mutation.ts
- projects/frontend/src/graphql/programmatic/add-artist-to-cache.ts
- projects/frontend/src/pages/share/PlaylistSongs.tsx
* update local artist cache if new artist has been added via song update
* fix position column width and pad with zeros (fix columns don't shrink)
* fix playlist songs order update shareid of songs missing
> fix: frontend various fixes and improvements

- .vscode/launch.json
- package.json
- projects/backend/src/auth/middleware/share-auth.ts
- projects/backend/src/index.ts
- projects/backend/src/utils/env/load-envs-from-file.ts
- projects/frontend/src/App.tsx
- projects/frontend/src/components/routing/Routing.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/components/sidebar/SidebarSection.tsx
- projects/frontend/src/player/PlayerContext.tsx
- projects/frontend/src/player/player-hook.ts
- projects/frontend/src/player/player.ts
* package.json add build:backend:watch script
* launch.json add entry for production instance debugging
* enable .env file for production environment
* destroy player on logout
* add playlist search filter
> chore: small changes and adjustments

- projects/backend/src/__test__/fixtures/song-query.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/database/versions/SchemaV1.ts
- projects/backend/src/inputs/IncreaseSongPlaycountInput.ts
- projects/backend/src/models/SongModel.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/backend/src/services/PlaylistService.ts
- projects/backend/src/services/SongService.ts
- projects/frontend/src/Apollo.ts
- projects/frontend/src/components/song-table/SongTableColumns.tsx
- projects/frontend/src/components/song-table/search/SongViewSettings.tsx
- projects/frontend/src/graphql/programmatic/increment-song-playcount.ts
- projects/frontend/src/graphql/types.ts
- projects/frontend/src/hooks/use-song-utils.ts
- projects/frontend/src/player/player.ts
**Backend**
* add share_songs play_count and update on increase song count call
* add play_count to select songs queries
**Frontend**
*  integrate increment song play count
* add play count column
> feature: basic song play count

- projects/backend/src/__test__/share-resolver.test.ts
- projects/backend/src/services/ShareService.ts
* on share create sync reference library songs
* fix leave share
* delete library song references from `share_songs` table a
* delete foreign songs referenced in own library playlists
> fix: backend create share reference library songs

- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/player/player.ts
* song table empty placeholder add custom description "No songs"
* player skip songs with no file source
* player fix end of song queue don't show network error
* player only propagate player deck error if primary deck
* if share playlist sidebar "all" links to share (not merged view)
> fix: frontend small improvements

- projects/backend/src/services/UserService.ts
- projects/frontend/src/Apollo.ts
- projects/frontend/src/components/song-table/SongTableColumns.tsx
- projects/frontend/src/pages/share/MainSongsView.tsx
- projects/frontend/src/pages/share/MergedSongs.tsx
- projects/frontend/src/pages/share/PlaylistSongs.tsx
- projects/frontend/src/pages/share/ShareSongs.tsx
- projects/frontend/src/pages/share/SongContextMenu.tsx
* fix invited user temporary name
* fix wrong song name in remove success message
* on network error show warning instead of redirect to offline page
* share and merged view indicate song share
> fix: various small frontend and backend fixes

- projects/backend/src/__test__/auth.test.ts
- projects/backend/src/__test__/aws-s3-file-service.test.ts
- projects/backend/src/__test__/azure-file-service.test.ts
- projects/backend/src/__test__/file-upload-resolver.test.ts
- projects/backend/src/__test__/mocks/ShareServiceMock.ts
- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/__test__/utils.test.ts
- projects/backend/src/__test__/utils/graphql.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/auth/auth-middleware.ts
- projects/backend/src/auth/middleware/auth-selectors.ts
- projects/backend/src/auth/middleware/permission-auth.ts
- projects/backend/src/file-service/AWSS3FileService.ts
- projects/backend/src/file-service/AzureFileService.ts
- projects/backend/src/file-service/FileService.ts
- projects/backend/src/file-service/file-service-utils.ts
- projects/backend/src/index.ts
- projects/backend/src/inputs/SubmitSongFromRemoteFileInput.ts
- projects/backend/src/resolvers/FileUploadResolver.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/backend/src/services/ShareService.ts
- projects/backend/src/types/context.ts
* `FileService.getLinkToFile()` add optional permission argument (`read | write`)
* `FileUploadResolver` add `generateUploadableUrl` mutation
* `SongResolver` add `submitSongFromRemoteFile` mutation
* graphql context inject user library object
> feature: backend support song submission from remote file

- projects/backend/src/__test__/graphql-middleware.test.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/middleware/SQLErrorInterceptor.ts
- projects/backend/src/server/GraphQLServer.ts
* add graphql middleware sql error interceptor
> feature: backend catch sql error

- projects/backend/src/__test__/mocks/SongServiceMock.ts
- projects/backend/src/__test__/user-resolver.test.ts
- projects/backend/src/database/seed.ts
- projects/backend/src/job-queues/SongUploadProcessingQueue.ts
- projects/backend/src/models/FileSourceModels.ts
- projects/backend/src/models/SongModel.ts
- projects/backend/src/resolvers/UserResolver.ts
- projects/backend/src/services/SongService.ts
* `FileUpload` add hash property
* song upload processing calc and store file hash
* `userResolver` add `findSongFileDuplicates` field resolver
> feature: backend store file hash and find duplicates

- projects/backend/src/index.ts
- projects/backend/src/types/Await.ts
- projects/backend/src/utils/background-tasks.ts
- projects/backend/src/utils/shutdown.ts
* add support for small background tasks
* add background tasks which adds missing file upload hashes
> feature: backend background tasks

- projects/frontend/src/components/modals/promt/Prompt.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettings.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/graphql/queries/share-users-query.ts
* on leave share redirect to root
* share settings user fetch from network only
* create share and playlist prompt submit on enter
> feature: frontend create share/playlist improvements

- projects/frontend/src/Apollo.ts
- projects/frontend/src/components/player/SongQueue.tsx
- projects/frontend/src/components/player/SongQueueItem.tsx
- projects/frontend/src/components/player/player-state.ts
- projects/frontend/src/components/sidebar/PlaylistContextMenu.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/graphql/mutations/create-playlist-mutation.ts
- projects/frontend/src/graphql/mutations/delete-playlist-mutation.ts
- projects/frontend/src/graphql/mutations/remove-song-from-library-mutation.ts
- projects/frontend/src/graphql/mutations/remove-songs-from-playlist-mutation.ts
- projects/frontend/src/pages/share/SongContextMenu.tsx
* player queue add clear queue button
* song queue item add remove button
* persist and restore player volume
* add remove from library to song context menu if song belongs to library
* merged view add create playlist button
> feature: frontend player queue clear/remove; persists player volume; merged view add create playlist button

- projects/frontend/src/components/modals/contextmenu/ContextMenu.tsx
- projects/frontend/src/components/sidebar/PlaylistContextMenu.tsx
- projects/frontend/src/components/sidebar/PlaylistSidebarItem.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/components/song-table/SongTable.tsx
- projects/frontend/src/components/song-table/SongTableColumns.tsx
- projects/frontend/src/components/song-table/SongTableHeader.tsx
- projects/frontend/src/components/song-table/search/SongViewSettings.tsx
- projects/frontend/src/components/upload/Dropzone.tsx
- projects/frontend/src/graphql/mutations/rename-playlist-mutation.ts
- projects/frontend/src/hooks/use-share-name.ts
- projects/frontend/src/pages/share/MainSongsView.tsx
- projects/frontend/src/pages/share/MergedSongs.tsx
- projects/frontend/src/pages/share/PlaylistSongs.tsx
- projects/frontend/src/pages/share/ShareSongs.tsx
- projects/frontend/src/pages/share/SongContextMenu.tsx
- projects/frontend/src/utils/upload/SongUploadContext.tsx
* playlist context menu add rename entry
* only show origin of song in merged view
* song view header add upload button
* improve context menu ux
* merged view playlists add share info on hover
> feature: frontend rename playlist; upload button; contextmenu ux

- package-lock.json
- package.json
- projects/shared-types/src/GeneratedTypes.ts
- projects/shared-types/src/UserStatus.ts
- projects/shared-types/src/Users.ts
- projects/shared-types/src/index.ts
* add simple-graphql-to-typescript dependency
* add auto generated types to shared types
Types will be integrated into codebase with the move from apollo client to react-query
> feature: setup auto generated types

- .gitignore
- projects/backend/package.json
- projects/frontend/package.json
- projects/react-graphql-client/.npmignore
- projects/react-graphql-client/package.json
- projects/react-graphql-client/src/remote/mutations/useAcceptInvitation.ts
- projects/react-graphql-client/src/remote/mutations/useChangePassword.ts
- projects/react-graphql-client/src/remote/mutations/useCreateShare.ts
- projects/react-graphql-client/src/remote/mutations/useDeletePlaylist.ts
- projects/react-graphql-client/src/remote/mutations/useDeleteShare.ts
- projects/react-graphql-client/src/remote/mutations/useGenerateUploadableUrl.ts
- projects/react-graphql-client/src/remote/mutations/useIncrementSongPlayCount.ts
- projects/react-graphql-client/src/remote/mutations/useInviteToShare.ts
- projects/react-graphql-client/src/remote/mutations/useLeaveShare.ts
- projects/react-graphql-client/src/remote/mutations/useRemoveSongFromLibrary.ts
- projects/react-graphql-client/src/remote/mutations/useRemoveSongsFromPlaylist.ts
- projects/react-graphql-client/src/remote/mutations/useRenamePlaylist.ts
- projects/react-graphql-client/src/remote/mutations/useRenameShare.ts
- projects/react-graphql-client/src/remote/mutations/useRestorePassword.ts
- projects/react-graphql-client/src/remote/mutations/useRevokeInvitation.ts
- projects/react-graphql-client/src/remote/mutations/useSongFileDuplicates.ts
- projects/react-graphql-client/src/remote/mutations/useSubmitSongFromRemoteFile.ts
- projects/react-graphql-client/src/remote/mutations/useUpdateAuth.ts
- projects/react-graphql-client/src/remote/mutations/useUpdatePlaylistSongOrder.ts
- projects/react-graphql-client/src/remote/mutations/useUpdateShareMemberPermissions.ts
* export all queries/mutations and interfaces
* version 1.0.1
> chore: release react-graphql-client v1.0.1

- projects/backend/src/__test__/song-resolver.test.ts
- projects/backend/src/job-queues/SongUploadProcessingQueue.ts
- projects/backend/src/resolvers/SongResolver.ts
- projects/react-graphql-client/package.json
- projects/react-graphql-client/src/remote/mutations/useSubmitSongFromRemoteFile.ts
* submitSongFromRemoteFile mutation return song
* bump @musicshare/react-graphql-client version to 1.0.2
> feature: submitSongFromRemoteFile return song

- projects/backend/src/__test__/user-resolver.test.ts
- projects/backend/src/__test__/utils/setup-test-env.ts
- projects/backend/src/args/duplicate-threshould.ts
- projects/backend/src/index.ts
- projects/backend/src/resolvers/ViewerResolver.ts
- projects/backend/src/services/SongService.ts
- projects/backend/src/services/services.ts
- projects/react-graphql-client/package.json
- projects/react-graphql-client/src/remote/mutations/useSongNearDuplicates.ts
* add optional theshold arg to findNearDuplicateSongs() field resolver
* add threshold arg to useSongNearDuplicates()
* react-graphql-client v1.0.4
> feature: find near duplicates add optional threshold arg

- .github/workflows/cd.staging.yaml
- .github/workflows/ci.build.yaml
- .github/workflows/dependabot_auto_merge.yaml
* staging release pipeline
* dependabot auto merge use strong github token
> chore: github actions releases

- .github/workflows/cd.production.yaml
- .github/workflows/cd.staging.yaml
* revert staging release docker login structure
* production release pipeline
> chore: production release pipeline

- .vscode/settings.json
- projects/frontend/src/GraphqlClientProvider.tsx
- projects/frontend/src/components/HeaderMenu.tsx
- projects/frontend/src/components/common/DefaultErrorResult.tsx
- projects/frontend/src/components/modals/ChangePasswordModal.tsx
- projects/frontend/src/components/modals/CreateShareModal.tsx
- projects/frontend/src/components/modals/share-settings/GenreSettings.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettings.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettingsGeneral.tsx
- projects/frontend/src/components/modals/share-settings/SongTypeSettings.tsx
- projects/frontend/src/components/modals/song-modal/SongForm.tsx
- projects/frontend/src/components/player/Player.tsx
- projects/frontend/src/components/sidebar/PlaylistContextMenu.tsx
- projects/frontend/src/components/sidebar/PlaylistSidebarItem.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/components/sidebar/SidebarItem.tsx
- projects/frontend/src/components/song-table/SongTableUI.tsx
- projects/frontend/src/components/song-table/search/SongSearch.tsx
- projects/frontend/src/pages/accept-invitation/AcceptInvitationForm.tsx
- projects/frontend/src/pages/login/Login.tsx
- projects/frontend/src/pages/login/LoginForm.tsx
- projects/frontend/src/pages/share/ShareSongs.tsx
- projects/frontend/src/utils/CommonCSS.ts
- projects/react-graphql-client/src/react-query-graphql.ts
- projects/react-graphql-client/src/remote/queries/useDirtyShareSongs.ts
**Changes:**
* login fix error hint and increase color contrast
* vscode settings fix search results
* remove unnecessary mutateAsync usages and catch others
* show network errors only for network errors
* type useQuery error to GraphQLClientError<TData>
* add DefaultErrorResult page
* fix error handling of ShareSongs
* disable text selection for songs and player
> feature: error handling improvements

- .github/workflows/cd.production.yaml
- .github/workflows/cd.staging.yaml
- .github/workflows/ci.build.yaml
- projects/backend/Dockerfile
- projects/frontend/Dockerfile
**Changes:**
* releases use build assets
* only production dependencies are installed
* set runner to ubuntu 18.04
> chore: reduce docker image size

- projects/react-graphql-client/src/remote/mutations/useUpdateSongType.ts
**Changes:**
* fix graphql client update song type mutation definition
> fix: graphql client update song type mutation definition

- .vscode/settings.json
- projects/frontend/src/components/modals/CreateShareModal.tsx
- projects/frontend/src/components/modals/share-settings/GenreSettings.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettings.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettingsGeneral.tsx
- projects/frontend/src/components/modals/share-settings/SongTypeSettings.tsx
- projects/frontend/src/components/modals/song-modal/SongForm.tsx
- projects/frontend/src/components/sidebar/PlaylistContextMenu.tsx
- projects/frontend/src/components/sidebar/PlaylistsSidebar.tsx
- projects/frontend/src/pages/restore-password/RestorePasswordForm.tsx
- projects/frontend/src/pages/share/SongContextMenu.tsx
- projects/react-graphql-client/src/GraphQLClient.ts
- projects/react-graphql-client/src/remote/mutations/useRemoveSongFromLibrary.ts
**Changes:**
* add error handler to mutations which are missing one
* fix share settings visibility according to user permissions
* set vscode auto import paths to relative
* remove song from library update all shares and merged songs
> fix: improve error and permission handling

- projects/frontend/src/components/HeaderMenu.tsx
- projects/frontend/src/components/modals/share-settings/ShareSettings.tsx
- projects/frontend/src/config.ts
**Changes:**
* add `REACT_APP_IS_DEMO` env var
* disable `Create Share`, `Leave Share`, `Change Password` if demo
> feature: add demo mode to frontend

- projects/backend/src/services/ShareService.ts
**Changes:**
* set share quota correctly after successful upload
> fix: update share quota
